#!/usr/bin/env bash
#Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

#Remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default
#Configure nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#Restart Nginx
sudo service nginx restart
